# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e3a2693305909f20786b9828942af6cceb0a5364b4cd2c5f696a998432e849fd08f5da67f9c6006d6bb4d0652ccdb2a5c37e2b42dc099858740e685d6f81af6

test:
  secret_key_base: 82db3c7aa65ec5fe0b3dc9c0b6a7e9aa89b8f273bf0b119df2e759e567e627b27dd26fa4d30eca0ccdff3e88c00a959947c1e856c894ea5d098beb1d8d711df9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
